### ISSUE TITLE
Log Message Contains All Metadata

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/cloudwatchlogs-java-appender#14]
I upgrade to 1.1.8.60 to get a hold of the custom MDC fields (thank you by the way)

However since, my messages in cloud watch are hard to read because they now contain all the meta data + the actual log message.

Before (version 1.1.5.46):
{
    "image": "[imagename]",
    "instance": "i-xxxxxxxx",
    "level": "WARN",
    "logger": "[logger]",
    "message": "[actual log message",
    "thread": "[threadid]"
}
Nice and clean...

After:

{
    "instance": "i-xxxxx",
    "image": "[image]",
    "level": "INFO",
    "message": "2018-02-01 18:07:27.579 boxfuse/xxx [application] {\"image\":\"[boxfuse image]\",\"instance\":\"i-xxxxxx\",\"level\":\"INFO\",\"logger\":\"[logger]\",\"message\":\"[THE LOG MESSAGE\"}"
}

Logback configuration is as follows:

	<appender name="cloud-watch" class="com.boxfuse.cloudwatchlogs.logback.CloudwatchLogsLogbackAppender">
		<config>
			<stdoutFallback>true</stdoutFallback>
			<customMdcKey>my-custom-mdc-key</customMdcKey>
		</config>
	</appender>

**Comment by axelfontaine** [comment]
It looks like the appender isn't being used to send the messages. Instead they are being sent to stdout and being picked up by the Go agent running outside the JVM. Now the interesting question is why...

Did anything else change in your setup?

**Comment by axelfontaine** [comment]
OK, this is the culprit: https://github.com/boxfuse/cloudwatchlogs-java-appender/blob/master/cloudwatchlogs-java-appender/src/main/java/com/boxfuse/cloudwatchlogs/internal/CloudwatchLogsLogEventPutter.java#L207

This should first check whether the sending to CloudWatch Logs is enabled, before attempting the fallback.

**Comment by axelfontaine** [comment]
This has now been fixed in 1.1.9.62.

**Comment by knocknarea** [comment]
Superb @axelfontaine
