### ISSUE TITLE
Document minimum version requirements for logging libraries

### ISSUE THREAD

**Issue by vdenisov** [boxfuse/cloudwatchlogs-java-appender#4]
For example, with Log4j2 ver. 2.6.2 (which we were using in production), appender failed on first logging statement with `Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.core.LogEvent.getContextData()Lorg/apache/logging/log4j/util/ReadOnlyStringMap;` - which is understandable, as it was only introduced in ver. 2.7, as far as I can see.

**Comment by axelfontaine** [comment]
Done. Thanks for the suggestion!
